---
abstract: 'RT-Extension-LifecycleUI Extension'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-LifecycleUI
no_index:
  directory:
    - html
    - inc
    - static
requires:
  RT::Extension::ConfigInDatabase: 0
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
x_module_install_rtx_version: 0.39
x_requires_rt: 4.4
x_requires_rt_plugins:
  - RT::Extension::ConfigInDatabase
x_rt_too_new: 4.6
